#!/usr/bin/env bash

set -eo pipefail

[[ -n "${VERBOSE}" ]] && set -x

while read -r plant; do
  while IFS="," read -r name common binomial family; do

    [[ -z "${binomial}" ]] && continue

    id=$(echo "${binomial}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)

    mkdir -p "data/${id}"

    jq -n \
      --arg id       "${id}"       \
      --arg name     "${name}"     \
      --arg common   "${common}"   \
      --arg binomial "${binomial}" \
      --arg family   "${family}"   \
      '{
        Id: $id,
        Description: "",
        Symptoms: [],
        Images: [],
        Name: $name,
        Binomial: $binomial,
        Common: $common | split("|"),
        Classification: {
          Kingdom: "",
          Clade: "",
          Order: "",
          Family: $family,
          Genus: "",
          Species: ""
        }
      }' > "data/${id}/${id}.json"
  done
done < <(tail -n +2 data/plants.csv)