#!/usr/bin/env bash

set -eo pipefail

[[ -n "${VERBOSE}" ]] && set -x

while read -r plant; do
  while IFS="," read -r common synonyms binomial family; do

    id=$(echo "${binomial}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)

    mkdir -p "data/${id}"

    jq -n \
      --arg id       "${id}"       \
      --arg common   "${common}"   \
      --arg synonyms "${synonyms}" \
      --arg binomial "${binomial}" \
      --arg family   "${family}"   \
      '{
        Id: $id,
        Description: "",
        Symptoms:    [],
        Images:      [],
        Names: {
          Common:   $common,
          Binomial: $binomial,
          Synonyms: $synonyms | split("|"),
        },
        Classification: {
          Kingdom: "",
          Clade:   "",
          Order:   "",
          Family:  $family,
          Genus:   "",
          Species: ""
        }
      }' > "data/${id}/data.json"
  done
done < <(tail -n +2 data/plants.csv)